### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by shreyas23** [GhiXu/ACMP#10]
Hey!

Are there any memory requirements for this codebase? I'm working with (~4000) 918x1368 images and often find the codebase exists with "Killed" indicating that I am running out of memory (128G) at some random point during the geometric consistency phase. Is this related to #4?

**Comment by RenDav** [comment]
I have the same question, why does the algorithm need so much memory.

**Comment by RenDavid** [comment]
> Hey!
> 
> Are there any memory requirements for this codebase? I'm working with (~4000) 918x1368 images and often find the codebase exists with "Killed" indicating that I am running out of memory (128G) at some random point during the geometric consistency phase. Is this related to #4?



> I have the same question, why does the algorithm need so much memory.

ACMP::~ACMP()
{
    delete[] plane_hypotheses_host;
    delete[] costs_host;
    imimages.clear();
    depths.clear();
    cameras.clear();ages.clear();
    depths.clear();
    cameras.clear();

> I have the same question, why does the algorithm need so much memory.

ACMP::~ACMP()
{
    delete[] plane_hypotheses_host;
    delete[] costs_host;
    **images.clear();
    depths.clear();
    cameras.clear();**

**Comment by RenDav** [comment]
https://github.com/GhiXu/ACMMP/issues/6#issue-1000251386
