### ISSUE TITLE
ACMMP algorithm on ETH3D dataset

### ISSUE THREAD

**Issue by CanCanZeng** [GhiXu/ACMP#8]
Hi, in the paper _Planar Prior Assisted PatchMatch Multi-View Stereo_ you say maybe you will combine ACMP with multi-scale strategy in the future, is the algorithm ACMMP the implementation? It looks like so from the name.

If you do not know about ACMMP, do you implement ACMP + ACMM yourself? Will it be much better than ACMP? And how about the speed?

**Comment by GhiXu** [comment]
Yeah, ACMMP is the implementation of ACMP with multi-scale strategy. The F1 score of ACMMP is better than ACMP, but its efficiency is worse than ACMP. The  related comparison can be seen from the ETH3D website.

**Comment by CanCanZeng** [comment]
Thank you for your immediate reply!

**Comment by CanCanZeng** [comment]
Hi, I still have a question, if my image resolution is rather low, for example no more than 640, then using multi-scale strategy will not promote the result, right?

**Comment by GhiXu** [comment]
As can be seen from the results on the low-res ETH3D many-view dataset, I think that multi-scale strategy can also improve the performance. However, compared with high-res input, the improvement for low-res input is relatively limited.
